try:
    f = open('test_file.txt')
except Exception:
    print(('Sorry. file does not exist'))
# else:
#     print('this session handled what code does if try block doesnt catch error)
# finally:
#     pass
    
'''
More general exception should be last
'''